Resources Used
- wget.download('https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/_downloads/da4babe668a8afb093cc7776d7e630f3/generate_tfrecord.py')
- Setup https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html

# 0. Setup Paths

In [1]:
WORKSPACE_PATH = 'Tensorflow/workspace'
SCRIPTS_PATH = 'Tensorflow/scripts'
APIMODEL_PATH = 'Tensorflow/models'
ANNOTATION_PATH = WORKSPACE_PATH+'/annotations'
IMAGE_PATH = WORKSPACE_PATH+'/images'
MODEL_PATH = WORKSPACE_PATH+'/models'
PRETRAINED_MODEL_PATH = WORKSPACE_PATH+'/pre-trained-models'
CONFIG_PATH = MODEL_PATH+'/my_ssd_mobnet/pipeline.config'
CHECKPOINT_PATH = MODEL_PATH+'/my_ssd_mobnet/'

In [2]:
import sys
sys.path.insert(0, 'C:\Projects\python\Game-SignLanguage\RealTimeObjectDetection\Tensorflow\models\research')
sys.path

['C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection\\Tensorflow\\models\research',
 'C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection',
 'C:\\Users\\Heidi\\anaconda3\\python38.zip',
 'C:\\Users\\Heidi\\anaconda3\\DLLs',
 'C:\\Users\\Heidi\\anaconda3\\lib',
 'C:\\Users\\Heidi\\anaconda3',
 '',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Heidi\\.ipython']

# 1. Create Label Map

In [ ]:
labels = [{'name': 'a', 'id': 1},
         {'name': 'b', 'id': 2},
         {'name': 'c', 'id': 3},
         {'name': 'd', 'id': 4},
         {'name': 'e', 'id': 5},
         {'name': 'f', 'id': 6},
         {'name': 'g', 'id': 7},
         {'name': 'h', 'id': 8},
         {'name': 'i', 'id': 9},
         {'name': 'j', 'id': 10},
         {'name': 'k', 'id': 11},
         {'name': 'l', 'id': 12},
         {'name': 'm', 'id': 13},
         {'name': 'n', 'id': 14},
         {'name': 'o', 'id': 15},
         {'name': 'p', 'id': 16},
         {'name': 'q', 'id': 17},
         {'name': 'r', 'id': 18},
         {'name': 's', 'id': 19},
         {'name': 't', 'id': 20},
         {'name': 'u', 'id': 21},
         {'name': 'v', 'id': 22},
         {'name': 'w', 'id': 23},
         {'name': 'x', 'id': 24},
         {'name': 'y', 'id': 25},
         {'name': 'z', 'id': 26}
]

with open(ANNOTATION_PATH + '\label_map.pbtxt', 'w') as f:
    for label in labels:
        f.write('item { \n')
        f.write('\tname:\'{}\'\n'.format(label['name']))
        f.write('\tid:{}\n'.format(label['id']))
        f.write('}\n')

# 2. Create TF records

In [3]:
import os

In [ ]:
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/train'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/train.record'}
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} -x {IMAGE_PATH + '/test'} -l {ANNOTATION_PATH + '/label_map.pbtxt'} -o {ANNOTATION_PATH + '/test.record'}

# 3. Download TF Models Pretrained Models from Tensorflow Model Zoo

In [ ]:
!cd Tensorflow && git clone https://github.com/tensorflow/models

In [ ]:
#wget.download('http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz')
#!mv ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz {PRETRAINED_MODEL_PATH}
#!cd {PRETRAINED_MODEL_PATH} && tar -zxvf ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz

# 4. Copy Model Config to Training Folder

In [4]:
CUSTOM_MODEL_NAME = 'my_ssd_mobnet' 

In [ ]:
print(PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config')
print(MODEL_PATH+'/'+CUSTOM_MODEL_NAME)

In [ ]:
!mkdir {'Tensorflow\workspace\models\\'+CUSTOM_MODEL_NAME}
!cp {PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config'} {MODEL_PATH+'/'+CUSTOM_MODEL_NAME}

# 5. Update Config For Transfer Learning

In [6]:
sys.path.insert(0, 'C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection\\Tensorflow\\models\\research')
sys.path

['C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection\\Tensorflow\\models\\research',
 'C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection\\Tensorflow\\models\research',
 'C:\\Projects\\python\\Game-SignLanguage\\RealTimeObjectDetection',
 'C:\\Users\\Heidi\\anaconda3\\python38.zip',
 'C:\\Users\\Heidi\\anaconda3\\DLLs',
 'C:\\Users\\Heidi\\anaconda3\\lib',
 'C:\\Users\\Heidi\\anaconda3',
 '',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Heidi\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Heidi\\.ipython']

In [7]:
import tensorflow as tf
from object_detection.utils import config_util
from object_detection.protos import pipeline_pb2
from google.protobuf import text_format

In [8]:
CONFIG_PATH = MODEL_PATH+'/'+CUSTOM_MODEL_NAME+'/pipeline.config'

In [9]:
config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

In [10]:
config

{'model': ssd {
   num_classes: 2
   image_resizer {
     fixed_shape_resizer {
       height: 320
       width: 320
     }
   }
   feature_extractor {
     type: "ssd_mobilenet_v2_fpn_keras"
     depth_multiplier: 1.0
     min_depth: 16
     conv_hyperparams {
       regularizer {
         l2_regularizer {
           weight: 4e-05
         }
       }
       initializer {
         random_normal_initializer {
           mean: 0.0
           stddev: 0.01
         }
       }
       activation: RELU_6
       batch_norm {
         decay: 0.997
         scale: true
         epsilon: 0.001
       }
     }
     use_depthwise: true
     override_base_feature_extractor_hyperparams: true
     fpn {
       min_level: 3
       max_level: 7
       additional_layer_depth: 128
     }
   }
   box_coder {
     faster_rcnn_box_coder {
       y_scale: 10.0
       x_scale: 10.0
       height_scale: 5.0
       width_scale: 5.0
     }
   }
   matcher {
     argmax_matcher {
       matched_threshold: 0.5
    

In [ ]:
pipeline_config = pipeline_pb2.TrainEvalPipelineConfig()
with tf.io.gfile.GFile(CONFIG_PATH, "r") as f:                                                                                                                                                                                                                     
    proto_str = f.read()                                                                                                                                                                                                                                          
    text_format.Merge(proto_str, pipeline_config)  

In [ ]:
pipeline_config.model.ssd.num_classes = 2
pipeline_config.train_config.batch_size = 4
pipeline_config.train_config.fine_tune_checkpoint = PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint/ckpt-0'
pipeline_config.train_config.fine_tune_checkpoint_type = "detection"
pipeline_config.train_input_reader.label_map_path= ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.train_input_reader.tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/train.record']
pipeline_config.eval_input_reader[0].label_map_path = ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.eval_input_reader[0].tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/test.record']

In [ ]:
config_text = text_format.MessageToString(pipeline_config)                                                                                                                                                                                                        
with tf.io.gfile.GFile(CONFIG_PATH, "wb") as f:                                                                                                                                                                                                                     
    f.write(config_text)   

# 6. Train the model

In [ ]:
print("""python {}/research/object_detection/model_main_tf2.py --model_dir={}/{} --pipeline_config_path={}/{}/pipeline.config --num_train_steps=10000""".format(APIMODEL_PATH, MODEL_PATH,CUSTOM_MODEL_NAME,MODEL_PATH,CUSTOM_MODEL_NAME))

# 7. Load Train Model From Checkpoint

In [7]:
!pip install tf-models-official

In [11]:
import os
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

In [12]:
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
detection_model = model_builder.build(model_config=configs['model'], is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(CHECKPOINT_PATH, 'ckpt-2')).expect_partial()

@tf.function
def detect_fn(image):
    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)
    return detections

# 8. Detect in Real-Time

In [13]:
import cv2 
import numpy as np

In [14]:
category_index = label_map_util.create_category_index_from_labelmap(ANNOTATION_PATH+'/label_map.pbtxt')

In [49]:
# Setup capture
cap = cv2.VideoCapture(0)
# width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
# height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [15]:
cap = cv2.VideoCapture(0)
while True: 
    ret, frame = cap.read()
    print(frame)
    image_np = np.array(frame)
    
    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
    detections = detect_fn(input_tensor)
    
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                  for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    label_id_offset = 1
    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
                image_np_with_detections,
                detections['detection_boxes'],
                detections['detection_classes']+label_id_offset,
                detections['detection_scores'],
                category_index,
                use_normalized_coordinates=True,
                max_boxes_to_draw=5,
                min_score_thresh=.5,
                agnostic_mode=False)

    cv2.imshow('object detection',  cv2.resize(image_np_with_detections, (800, 600)))
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cap.release()
        break
cap.release()
cv2.destroyAllWindows()

[[[ 94  92  72]
  [ 95  93  73]
  [ 93  90  79]
  ...
  [ 94  97  89]
  [ 94  96  91]
  [ 94  96  91]]

 [[112 109  89]
  [112 109  89]
  [110 106  96]
  ...
  [ 94  97  89]
  [ 94  96  91]
  [ 94  96  91]]

 [[107 102  89]
  [107 102  89]
  [107 102  89]
  ...
  [ 93  95  90]
  [ 93  96  88]
  [ 93  96  88]]

 ...

 [[133 130 119]
  [133 130 119]
  [135 132 114]
  ...
  [109 107  98]
  [ 84  77  69]
  [ 84  77  69]]

 [[131 131 117]
  [132 132 118]
  [133 131 117]
  ...
  [122 125 116]
  [ 84  72  67]
  [ 85  73  69]]

 [[132 132 118]
  [132 132 118]
  [133 131 117]
  ...
  [125 128 118]
  [ 83  71  66]
  [ 85  73  69]]]


error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1drr4hl0\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [ ]:
input_tensor

In [ ]:
from matplotlib import pyplot as plt

In [43]:
image_np

array(None, dtype=object)

In [19]:
cv2.resize(image_np_with_detections, (800, 600))

array([[[ 94,  92,  72],
        [ 94,  93,  73],
        [ 94,  91,  76],
        ...,
        [ 94,  96,  90],
        [ 94,  96,  91],
        [ 94,  96,  91]],

       [[106, 104,  84],
        [107, 104,  84],
        [106, 103,  88],
        ...,
        [ 94,  96,  90],
        [ 94,  96,  91],
        [ 94,  96,  91]],

       [[110, 106,  89],
        [110, 106,  89],
        [109, 105,  91],
        ...,
        [ 94,  96,  90],
        [ 94,  96,  90],
        [ 94,  96,  90]],

       ...,

       [[132, 131, 118],
        [132, 131, 118],
        [133, 131, 117],
        ...,
        [100,  95,  88],
        [ 84,  75,  68],
        [ 85,  75,  69]],

       [[131, 131, 117],
        [132, 132, 118],
        [132, 131, 117],
        ...,
        [103,  99,  92],
        [ 84,  72,  67],
        [ 85,  73,  69]],

       [[132, 132, 118],
        [132, 132, 118],
        [132, 131, 117],
        ...,
        [104,  99,  92],
        [ 83,  71,  67],
        [ 85,  73,  69]]

In [22]:
!pip install --upgrade opencv-python

Requirement already up-to-date: opencv-python in c:\users\heidi\anaconda3\lib\site-packages (4.5.1.48)


In [23]:
cv2.imshow('objectdetection',  cv2.resize(image_np_with_detections, (800, 600)))

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1drr4hl0\opencv\modules\highgui\src\window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [16]:
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-1drr4hl0\opencv\modules\highgui\src\window.cpp:645: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'


In [ ]:
!conda remove opencv
!conda update conda
!conda install --channel menpo opencv